import type { TemplateConfig, ShapeConfig } from "@/lib/types";
import { DARBARTECH_CERTIFICATE_TEMPLATE } from "./darbartech-certificate-v1";

const page = {
  width: 297,
  height: 210,
  unit: "mm" as const,
  dpi: 300,
  orientation: "landscape" as const,
  colorMode: "CMYK" as const,
};

const safeArea = {
  topMm: 8,
  rightMm: 8,
  bottomMm: 8,
  leftMm: 8,
};

const colors = {
  deepNavy: { cmyk: "96,82,44,44", hex: "#061A50", hexSrgb: "#152B48" },
  corporateBlue: { cmyk: "91,56,26,6", hex: "#1669B2", hexSrgb: "#0F668F" },
  teal: { cmyk: "80,23,21,0", hex: "#34C5CA", hexSrgb: "#0099B8" },
  bodyInk: { cmyk: "75,68,67,90", hex: "#060808", hexSrgb: "#010203" },
  white: { cmyk: "0,0,0,0", hex: "#FFFFFF", hexSrgb: "#FFFFFF" },
};

const moduleConstraints = {
  minCount: 4,
  maxCount: 4,
  maxTitleLength: 45,
  maxSubtitleLength: 80,
  area: {
    x: 26.9,
    y: 120.0,
    width: 243.2,
    height: 16.0,
    gap: 2,
  },
  item: {
    titleFont: "Montserrat-SemiBold",
    titleSize: 12,
    titleWeight: "600",
    titleColor: colors.deepNavy.hexSrgb,
    subtitleFont: "Montserrat-SemiBold",
    subtitleSize: 10,
    subtitleWeight: "600",
    subtitleColor: colors.corporateBlue.hexSrgb,
    alignment: "center" as const,
  },
};

const staticAssets = {
  logo: "/logo.png",
  watermarkLogo: "/logo-small.png",
  background: undefined,
  border: undefined,
};

const qrConfig = {
  x: 254.4,
  y: 11.2,
  size: 11.6,
  errorCorrection: "M" as const,
  margin: 1,
  borderMm: 0.3,
  borderColor: colors.corporateBlue.hexSrgb,
};

// FR-11 layering is expressed per-shape via `layer` (ascending draw order; higher = drawn later = on top).
// Task 5's renderer reads these tags to draw each group at its pipeline step. Rationale for every
// tuned value is recorded inline; because exact mm measurements were unavailable, all new coordinates
// are documented approximations of the Aayara reference composition.
//
// IMPORTANT (BUG-11 / T25): All stroke/fill colour values in this file reference the `colors.*.hexSrgb`
// palette token — NEVER hard-code a literal `"#1669B2"` / `"#0F668F"` / `"#34C5CA"` / `"#061A50"` string
// directly. A one-off literal bypasses the Round-1 sRGB calibration and drifts silently on every palette
// correction. The renderer asserts against those four literals at PDF-write time; a hard-coded string
// there will fail the render with a T25 violation.
const shapes: ShapeConfig[] = [
  // ── Layer 1 · outer frame ────────────────────────────────────────
  // BUG-13 (Round 4): 0.20 mm still anti-aliased to ~65% opacity — a line centered
  // exactly on a pixel boundary at 150 dpi needs >=2 device px (0.34 mm) of width to
  // guarantee one full-ink pixel regardless of where its center falls on the grid.
  // 0.20 mm (~1.18 px) was below that floor. Bumped to 0.35 mm.
  { kind: "rect", x: 8.0, y: 6.5, width: 281.8, height: 196.4,
    stroke: colors.corporateBlue.hexSrgb, strokeWidthMm: 0.35, layer: 1 },

  // ── Layer 2 · top-left corner group (§6.1) ───────────────────────
  // Navy wedge. Hypotenuse x = 17.9 − 1.10·y. Bleeds off top + left trim.
  { kind: "polygon", layer: 2, fill: colors.deepNavy.hexSrgb, points: [
      { x: -5.0, y: -5.0 },
      { x: 23.4, y: -5.0 },
      { x: -5.0, y: 20.8 },
  ]},
  // Blue parallel band, 2.0 mm clear of the wedge, 6.94 mm horizontal width.
  { kind: "polygon", layer: 2, fill: colors.corporateBlue.hexSrgb, points: [
      { x: 25.1, y: -5.0 },
      { x: 32.1, y: -5.0 },
      { x: -5.0, y: 28.8 },
      { x: -5.0, y: 22.5 },
  ]},
  // White accent bar — cuts a horizontal slit through the blue band.
  { kind: "rect", layer: 2, x: 9.1, y: 8.0, width: 14.2, height: 1.4, fill: colors.white.hexSrgb },

  // ── Layer 3 · rules, dividers, diamond ───────────────────────────
  { kind: "line", orientation: "horizontal", x: 85.9, y: 55.1, width: 23.0, height: 0,
    stroke: colors.teal.hexSrgb, strokeWidthMm: 0.17, layer: 3 },
  { kind: "line", orientation: "horizontal", x: 191.9, y: 55.1, width: 23.0, height: 0,
    stroke: colors.teal.hexSrgb, strokeWidthMm: 0.17, layer: 3 },

  // Name flanks — See §11. Renderer draws these DYNAMICALLY after measuring the
  // recipient name ink width, clamping span 132–190 mm with a 3.4 mm diamond gap.
  // (Static placeholders removed per CERTIFICATE_DESIGN_PARITY_SPEC.md §11.)

  // FIX BUG-06: diamond as an explicit polygon centred on (150.0, 78.2),
  // bbox 2.7 × 2.7 mm. The old rotated rect pivoted on its bottom-left corner,
  // which pushed it 1.7 mm up and inflated it to 4.57 mm — it collided with
  // the recipient name.
  { kind: "polygon", layer: 3, fill: colors.teal.hexSrgb, points: [
      { x: 150.00, y: 76.85 },
      { x: 151.35, y: 78.20 },
      { x: 150.00, y: 79.55 },
      { x: 148.65, y: 78.20 },
  ]},

  { kind: "line", orientation: "horizontal", x: 88.2, y: 114.0, width: 36.6, height: 0,
    stroke: colors.teal.hexSrgb, strokeWidthMm: 0.17, layer: 3 },
  { kind: "line", orientation: "horizontal", x: 179.0, y: 114.0, width: 36.6, height: 0,
    stroke: colors.teal.hexSrgb, strokeWidthMm: 0.17, layer: 3 },

  // Module column dividers — MUST be vertical (reference: constant x, y 128.1–133.9).
  // BUG-09: 0.22 mm stroke (was 0.17) for solid anti-aliased pixel coverage.
  // BUG-12 #3 audit: exactly one declaration per divider; all three share identical
  // y=128.1 height=5.8 so the visual appearance is uniform across columns.
  // BUG-11: colour resolved through the palette token so Round-1 sRGB calibration
  // always applies (formerly hard-coded to the pre-correction #1669B2 literal).
  // BUG-13 (Round 4): 0.22 mm (~1.3 px) rendered solid for #1/#2 but only ~83% for #3 —
  // same nominal width, different opacity, because each x sits differently relative to
  // the 150-dpi pixel grid. 0.22 mm was below the 2-device-px (0.34 mm) floor needed to
  // guarantee full ink regardless of alignment. All three bumped uniformly to 0.35 mm
  // so there's no outlier between columns (see T23).
  { kind: "line", orientation: "vertical", x: 87.1, y: 128.1, width: 0, height: 5.8,
    stroke: colors.corporateBlue.hexSrgb, strokeWidthMm: 0.35, layer: 3 },
  { kind: "line", orientation: "vertical", x: 150.1, y: 128.1, width: 0, height: 5.8,
    stroke: colors.corporateBlue.hexSrgb, strokeWidthMm: 0.35, layer: 3 },
  { kind: "line", orientation: "vertical", x: 216.6, y: 128.1, width: 0, height: 5.8,
    stroke: colors.corporateBlue.hexSrgb, strokeWidthMm: 0.35, layer: 3 },

  // QR separator.
  { kind: "line", orientation: "vertical", x: 250.7, y: 12.0, width: 0, height: 13.8,
    stroke: colors.corporateBlue.hexSrgb, strokeWidthMm: 0.30, layer: 3 },

  // Date / signature underlines (x=43.3 date, x=139.4 signatory-1, x=216.0 signatory-2) —
  // BUG-12: 0.15 mm (was 0.10) still measured at 58–76% opacity (Round 4 audit).
  // BUG-13 (Round 4): same 2-device-px floor as the frame/dividers above — 0.15 mm
  // (~0.89 px) is below one full pixel, let alone the 0.34 mm needed to guarantee full
  // ink regardless of pixel-grid alignment. Bumped to 0.35 mm.
  { kind: "line", orientation: "horizontal", x: 43.3, y: 176.0, width: 26.4, height: 0,
    stroke: colors.corporateBlue.hexSrgb, strokeWidthMm: 0.35, layer: 3 },
  { kind: "line", orientation: "horizontal", x: 139.4, y: 176.0, width: 28.1, height: 0,
    stroke: colors.corporateBlue.hexSrgb, strokeWidthMm: 0.35, layer: 3 },
  { kind: "line", orientation: "horizontal", x: 216.0, y: 176.2, width: 38.2, height: 0,
    stroke: colors.corporateBlue.hexSrgb, strokeWidthMm: 0.35, layer: 3 },

  // ── Layer 4 · footer bar (§6.2) ──────────────────────────────────
  // Right edge is a DIAGONAL: x = 231.5 − 1.40·(y − 192).
  // Reverts the v2 widening to 281.8, which flattened the corner composition.
  { kind: "polygon", layer: 4, fill: colors.corporateBlue.hexSrgb, points: [
      { x: 7.6, y: 191.68 },
      { x: 231.9, y: 191.68 },
      { x: 214.9, y: 203.87 },
      { x: 7.6, y: 203.87 },
  ]},
  // Footer ticks — these ARE slanted in the reference. Left as legacy diagonals.
  { kind: "line", x: 35.6, y: 196.8, width: 0.4, height: 4.1,
    stroke: colors.white.hexSrgb, strokeWidthMm: 0.03, layer: 4 },
  { kind: "line", x: 73.6, y: 196.8, width: 0.4, height: 4.1,
    stroke: colors.white.hexSrgb, strokeWidthMm: 0.03, layer: 4 },

  // ── Layer 5 · bottom-right corner group (§6.2) ───────────────────
  // Free-floating blue accent band above the footer.
  { kind: "polygon", layer: 5, fill: colors.corporateBlue.hexSrgb, points: [
      { x: 286.3, y: 177.0 },
      { x: 290.8, y: 177.0 },
      { x: 273.4, y: 189.5 },
      { x: 268.9, y: 189.5 },
  ]},
  // Navy corner block. Bleeds off the RIGHT trim only; bottom is a hard edge.
  // The ~3.8 mm white sliver between this and the footer-blue is intentional.
  { kind: "polygon", layer: 5, fill: colors.deepNavy.hexSrgb, points: [
      { x: 302.0, y: 180.9 },
      { x: 280.0, y: 193.1 },
      { x: 233.7, y: 193.1 },
      { x: 218.4, y: 203.87 },
      { x: 302.0, y: 203.87 },
  ]},

  // ── Layer 6 · grade badge ────────────────────────────────────────
  // FIX §8: full pill, r = height / 2. Was 1.5 mm, which rendered as a
  // near-square box against the reference's semicircular caps.
  { kind: "rect", layer: 6, x: 122.9, y: 155.3, width: 50.4, height: 8.6,
    fill: colors.teal.hexSrgb, stroke: colors.corporateBlue.hexSrgb, strokeWidthMm: 0.02, cornerRadiusMm: 4.3 },
];

const stubField = (name: string) => ({
  field: name,
  type: "text" as const,
  x: 0,
  y: 0,
  width: 1,
  height: 1,
  font: "",
  fontSize: 0,
  weight: "normal" as const,
  color: "",
  alignment: "left" as const,
  maxLines: 1,
  minFontSize: 0,
  overflowPolicy: "reject" as const,
  required: false,
});

const fields = {
  heroHeadline: {
    field: "heroHeadline",
    type: "text" as const,
    x: 57.3,
    y: 39.4,
    width: 181.5,
    height: 8.1,
    font: "Montserrat-ExtraBold",
    fontSize: 32,
    weight: "extra-bold",
    color: colors.deepNavy.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 3.0,
    maxLines: 1,
    minFontSize: 21.6,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
    runs: [
      { text: "", font: "Montserrat-ExtraBold", fontSize: 32, color: colors.deepNavy.hexSrgb },
      { text: "", font: "Montserrat-ExtraBold", fontSize: 32, color: colors.corporateBlue.hexSrgb },
    ],
  },
  salutation: {
    field: "salutation",
    type: "text" as const,
    x: 109.3,
    y: 53.9,
    width: 77.6,
    height: 2.7,
    font: "Montserrat-SemiBold",
    fontSize: 11,
    weight: "600",
    color: colors.bodyInk.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 290,
    maxLines: 1,
    minFontSize: 7.2,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
  },
  recipientName: {
    field: "recipientName",
    type: "text" as const,
    x: 59.8,
    y: 64.0,
    width: 180.0,
    height: 10.8,
    font: "CormorantGaramond-Bold",
    fontSize: 46,
    weight: "bold",
    color: colors.deepNavy.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 25,
    maxLines: 1,
    minFontSize: 24.0,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
  },
  postRecipientText: {
    field: "postRecipientText",
    type: "text" as const,
    x: 114.6,
    y: 81.5,
    width: 66.9,
    height: 4.1,
    font: "Montserrat-Regular",
    fontSize: 12,
    weight: "normal",
    color: colors.bodyInk.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 10,
    maxLines: 1,
    minFontSize: 8.4,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
  },
  programTitle: {
    field: "programTitle",
    type: "text" as const,
    x: 69.8,
    y: 92.0,
    width: 180.2,
    height: 4.3,
    font: "Montserrat-SemiBold",
    fontSize: 17,
    weight: "600",
    color: colors.deepNavy.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 18,
    maxLines: 1,
    minFontSize: 12,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
  },
  durationSentence: {
    field: "durationSentence",
    type: "text" as const,
    x: 26.9,
    y: 101.3,
    width: 252.1,
    height: 3.8,
    font: "Montserrat-SemiBold",
    fontSize: 11,
    weight: "600",
    color: colors.bodyInk.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 7.7,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    runs: [
      { text: "", font: "Montserrat-SemiBold", fontSize: 11, color: colors.corporateBlue.hexSrgb },
      { text: "", font: "Montserrat-SemiBold", fontSize: 11, color: colors.bodyInk.hexSrgb },
      { text: "", font: "Montserrat-SemiBold", fontSize: 11, color: colors.corporateBlue.hexSrgb },
      { text: "", font: "Montserrat-SemiBold", fontSize: 11, color: colors.bodyInk.hexSrgb },
    ],
  },
  courseModulesHeading: {
    field: "courseModulesHeading",
    type: "text" as const,
    x: 127.8,
    y: 112.8,
    width: 47.5,
    height: 2.7,
    font: "Montserrat-SemiBold",
    fontSize: 11,
    weight: "600",
    color: colors.deepNavy.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 210,
    maxLines: 1,
    minFontSize: 7.2,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
  },
  module1Numeral: {
    field: "module1Numeral",
    type: "text" as const,
    x: 50.6,
    y: 121.4,
    width: 6.3,
    height: 4.6,
    font: "Montserrat-ExtraBold",
    fontSize: 18,
    weight: "extra-bold",
    color: colors.corporateBlue.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 12,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
  },
  module2Numeral: {
    field: "module2Numeral",
    type: "text" as const,
    x: 114.4,
    y: 121.7,
    width: 8.0,
    height: 4.6,
    font: "Montserrat-ExtraBold",
    fontSize: 18,
    weight: "extra-bold",
    color: colors.corporateBlue.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 12,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
  },
  module3Numeral: {
    field: "module3Numeral",
    type: "text" as const,
    x: 178.2,
    y: 121.7,
    width: 7.8,
    height: 4.6,
    font: "Montserrat-ExtraBold",
    fontSize: 18,
    weight: "extra-bold",
    color: colors.corporateBlue.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 12,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
  },
  module4Numeral: {
    field: "module4Numeral",
    type: "text" as const,
    x: 245.6,
    y: 121.4,
    width: 8.6,
    height: 4.6,
    font: "Montserrat-ExtraBold",
    fontSize: 18,
    weight: "extra-bold",
    color: colors.corporateBlue.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 12,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
  },
  module1Title: {
    field: "module1Title",
    type: "text" as const,
    x: 26.9,
    y: 128.9,
    width: 53.7,
    height: 2.5,
    font: "Montserrat-SemiBold",
    fontSize: 10,
    weight: "600",
    color: colors.deepNavy.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 10,
    maxLines: 1,
    minFontSize: 6.7,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
  },
  module2Title: {
    field: "module2Title",
    type: "text" as const,
    x: 97.2,
    y: 129.0,
    width: 42.2,
    height: 2.5,
    font: "Montserrat-SemiBold",
    fontSize: 10,
    weight: "600",
    color: colors.deepNavy.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 10,
    maxLines: 1,
    minFontSize: 6.7,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
  },
  module3Title: {
    field: "module3Title",
    type: "text" as const,
    x: 166.0,
    y: 129.2,
    width: 32.3,
    height: 2.5,
    font: "Montserrat-SemiBold",
    fontSize: 10,
    weight: "600",
    color: colors.deepNavy.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 10,
    maxLines: 1,
    minFontSize: 6.7,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
  },
  module4Title: {
    field: "module4Title",
    type: "text" as const,
    x: 235.9,
    y: 129.0,
    width: 28.1,
    height: 2.5,
    font: "Montserrat-SemiBold",
    fontSize: 10,
    weight: "600",
    color: colors.deepNavy.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 10,
    maxLines: 1,
    minFontSize: 6.7,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
  },
  module1Subtitle: {
    field: "module1Subtitle",
    type: "text" as const,
    x: 33.4,
    y: 133.3,
    width: 40.6,
    height: 2.7,
    font: "Montserrat-SemiBold",
    fontSize: 8,
    weight: "600",
    color: colors.corporateBlue.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.3,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
  },
  module2Subtitle: {
    field: "module2Subtitle",
    type: "text" as const,
    x: 92.0,
    y: 133.4,
    width: 52.6,
    height: 2.7,
    font: "Montserrat-SemiBold",
    fontSize: 8,
    weight: "600",
    color: colors.corporateBlue.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.3,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
  },
  module3Subtitle: {
    field: "module3Subtitle",
    type: "text" as const,
    x: 154.6,
    y: 133.7,
    width: 55.1,
    height: 2.6,
    font: "Montserrat-SemiBold",
    fontSize: 8,
    weight: "600",
    color: colors.corporateBlue.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.3,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
  },
  module4Subtitle: {
    field: "module4Subtitle",
    type: "text" as const,
    x: 224.2,
    y: 133.7,
    width: 51.5,
    height: 2.7,
    font: "Montserrat-SemiBold",
    fontSize: 8,
    weight: "600",
    color: colors.corporateBlue.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.3,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
  },
  completionStatement: {
    field: "completionStatement",
    type: "text" as const,
    x: 64.3,
    y: 142.3,
    width: 168.1,
    height: 8.2,
    capHeightMm: 2.6,
    font: "Montserrat-Regular",
    fontSize: 10,
    weight: "normal",
    color: colors.bodyInk.hexSrgb,
    alignment: "center" as const,
    lineHeight: 1.3,
    letterSpacing: 10,
    maxLines: 2,
    minFontSize: 6.7,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
  },
  gradeBadgeText: {
    field: "gradeBadgeText",
    type: "text" as const,
    x: 127.4,
    y: 157.1,
    width: 41.4,
    height: 5.1,
    font: "Montserrat-SemiBold",
    fontSize: 10,
    weight: "600",
    color: colors.white.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 160,
    maxLines: 1,
    minFontSize: 7.2,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
    transformUppercase: true,
    runs: [
      { text: "", font: "Montserrat-SemiBold", fontSize: 10, color: colors.white.hexSrgb },
      { text: "", font: "Montserrat-ExtraBold", fontSize: 18, color: colors.white.hexSrgb },
    ],
  },
  // ── Top-right metadata block (GAP-05 / FR-4) ──────────────
  // Replaces the old combined certMetaLabels / certNumberAndDateValue pair (both demoted to stubs
  // below). Four explicit label/value fields on two rows, 3.0 mm apart, all left of the QR separator
  // at x=250.4. Labels (SemiBold) and values (Medium) are horizontally paired on each row.
  certNumberLabel: {
    field: "certNumberLabel",
    type: "text" as const,
    x: 189.0,
    y: 13.3,
    width: 26.0,
    height: 2.2,
    font: "Montserrat-SemiBold",
    fontSize: 8.5,
    weight: "600",
    color: colors.bodyInk.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.5,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: false,
  },
  certNumberValue: {
    field: "certNumberValue",
    type: "text" as const,
    x: 218.0,
    y: 13.3,
    width: 33.5,
    height: 2.2,
    font: "Montserrat-Medium",
    fontSize: 8.5,
    weight: "500",
    color: colors.bodyInk.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.5,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: false,
  },
  issueDateMetaLabel: {
    field: "issueDateMetaLabel",
    type: "text" as const,
    x: 189.0,
    y: 17.1,
    width: 26.0,
    height: 2.2,
    font: "Montserrat-SemiBold",
    fontSize: 8.5,
    weight: "600",
    color: colors.bodyInk.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.5,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: false,
  },
  issueDateMetaValue: {
    field: "issueDateMetaValue",
    type: "text" as const,
    x: 218.0,
    y: 17.1,
    width: 33.5,
    height: 2.2,
    font: "Montserrat-Medium",
    fontSize: 8.5,
    weight: "500",
    color: colors.bodyInk.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.5,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: false,
  },
  qrCaption1: {
    field: "qrCaption1",
    type: "text" as const,
    x: 254.2,
    y: 25.9,
    width: 33.4,
    height: 1.9,
    font: "Montserrat-Bold",
    fontSize: 8,
    weight: "bold",
    color: colors.bodyInk.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.3,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
    transformUppercase: true,
  },
  qrCaption2a: {
    field: "qrCaption2a",
    type: "text" as const,
    x: 254.1,
    y: 29.7,
    width: 34.9,
    height: 2.0,
    font: "Montserrat-Regular",
    fontSize: 7,
    weight: "normal",
    color: colors.bodyInk.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 4.8,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
  },
  qrCaption2b: {
    field: "qrCaption2b",
    type: "text" as const,
    x: 254.1,
    y: 32.6,
    width: 34.9,
    height: 2.0,
    font: "Montserrat-Regular",
    fontSize: 7,
    weight: "normal",
    color: colors.bodyInk.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 4.8,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
  },
  qrCaption2c: {
    field: "qrCaption2c",
    type: "text" as const,
    x: 254.1,
    y: 35.5,
    width: 34.9,
    height: 2.0,
    font: "Montserrat-Regular",
    fontSize: 7,
    weight: "normal",
    color: colors.bodyInk.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 4.8,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
    transformUppercase: false,
  },
  issueDateLabel: {
    field: "issueDateLabel",
    type: "text" as const,
    x: 44.5,
    y: 177.9,
    width: 25.1,
    height: 2.2,
    font: "Montserrat-SemiBold",
    fontSize: 9,
    weight: "600",
    color: colors.bodyInk.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 10,
    maxLines: 1,
    minFontSize: 6,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
    transformUppercase: true,
  },
  issueDateValue: {
    field: "issueDateValue",
    type: "text" as const,
    x: 42.0,
    y: 182.5,
    width: 29.5,
    height: 2.0,
    font: "Montserrat-Regular",
    fontSize: 8,
    weight: "normal",
    color: colors.bodyInk.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.3,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
  },
  signatory1Label: {
    field: "signatory1Label",
    type: "text" as const,
    x: 131.4,
    y: 177.9,
    width: 43.0,
    height: 2.2,
    font: "Montserrat-SemiBold",
    fontSize: 9,
    weight: "600",
    color: colors.bodyInk.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 10,
    maxLines: 1,
    minFontSize: 6,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
    transformUppercase: true,
  },
  signatory1Name: {
    field: "signatory1Name",
    type: "text" as const,
    x: 142.8,
    y: 183.4,
    width: 18.2,
    height: 2.1,
    font: "Montserrat-Regular",
    fontSize: 8,
    weight: "normal",
    color: colors.bodyInk.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.3,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
  },
  signatory2Label: {
    field: "signatory2Label",
    type: "text" as const,
    x: 216.6,
    y: 178.6,
    width: 37.1,
    height: 2.2,
    font: "Montserrat-SemiBold",
    fontSize: 9,
    weight: "600",
    color: colors.bodyInk.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 10,
    maxLines: 1,
    minFontSize: 6,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
    transformUppercase: true,
  },
  signatory2Name: {
    field: "signatory2Name",
    type: "text" as const,
    x: 221.5,
    y: 183.6,
    width: 24.0,
    height: 2.1,
    font: "Montserrat-Regular",
    fontSize: 8,
    weight: "normal",
    color: colors.bodyInk.hexSrgb,
    alignment: "center" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.3,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
  },
  footerVerified: {
    field: "footerVerified",
    type: "text" as const,
    x: 37.2,
    y: 198.3,
    width: 33.8,
    height: 1.5,
    font: "Montserrat-SemiBold",
    fontSize: 7.9,
    weight: "600",
    color: colors.white.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.3,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
    transformUppercase: true,
  },
  footerCertNumber: {
    field: "footerCertNumber",
    type: "text" as const,
    x: 75.5,
    y: 198.0,
    width: 53.5,
    height: 1.4,
    font: "Montserrat-Regular",
    fontSize: 7.9,
    weight: "normal",
    color: colors.white.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 5.3,
    overflowPolicy: "shrink_then_reject" as const,
    required: true,
    transformUppercase: true,
  },
  footerContact: {
    field: "footerContact",
    type: "text" as const,
    x: 136.1,
    y: 197.6,
    width: 83.1,
    height: 2.4,
    font: "Montserrat-Medium",
    fontSize: 7,
    weight: "500",
    color: colors.white.hexSrgb,
    alignment: "left" as const,
    letterSpacing: 0,
    maxLines: 1,
    minFontSize: 4.8,
    overflowPolicy: "shrink_then_reject" as const,
    required: false,
  },
  // Demoted to stubs for v2: replaced by the four explicit metadata fields (certNumberLabel,
  // certNumberValue, issueDateMetaLabel, issueDateMetaValue) above.
  certMetaLabels: stubField("certMetaLabels"),
  certNumberAndDateValue: stubField("certNumberAndDateValue"),
  // Demoted to stub for v2: replaced by qrCaption2a / qrCaption2b / qrCaption2c above.
  qrCaption2: stubField("qrCaption2"),
  mainTitle: stubField("mainTitle"),
  mainSubtitle: stubField("mainSubtitle"),
  preRecipientText: stubField("preRecipientText"),
  postRecipientLine: stubField("postRecipientLine"),
  programTitle_old: stubField("programTitle_old"),
  duration: stubField("duration"),
  completionLabel: stubField("completionLabel"),
  completionDate: stubField("completionDate"),
  issueLabel: stubField("issueLabel"),
  issueDate: stubField("issueDate"),
  gradeLabel: stubField("gradeLabel"),
  grade: stubField("grade"),
  signatoryName: stubField("signatoryName"),
  signatoryLine: stubField("signatoryLine"),
  signatoryPosition: stubField("signatoryPosition"),
  certificateNumberLabel: stubField("certificateNumberLabel"),
  certificateNumber: stubField("certificateNumber"),
  footerText: stubField("footerText"),
  issuedBy: stubField("issuedBy"),
  issuerLogo: {
    field: "issuerLogo",
    type: "image" as const,
    x: 43.6,
    y: 12.8,
    width: 84.2,
    height: 16.3,
    font: "",
    fontSize: 0,
    weight: "normal" as const,
    color: "",
    alignment: "center" as const,
    maxLines: 1,
    minFontSize: 0,
    overflowPolicy: "reject" as const,
    required: false,
  },
};

export const DARBARTECH_CERTIFICATE_TEMPLATE_V2: TemplateConfig = {
  templateId: "darbartech-certificate",
  version: "2.0.0",
  rendererVersion: "certificate-engine 2.0.0",
  page,
  safeArea,
  moduleConstraints,
  fields,
  staticAssets,
  qrConfig,
  signatureConfig: {
    x: 178,
    y: 166,
    width: 100,
    height: 16,
    nameFont: "Montserrat-Bold",
    nameSize: 10,
    nameWeight: "bold",
    positionFont: "Montserrat-Regular",
    positionSize: 8,
  },
  shapes,
  colors,
};

export const DEFAULT_PUBLIC_FIELDS_V2 = {
  certificateNumber: true,
  recipientName: true,
  programTitle: true,
  duration: true,
  trainingProvider: true,
  completionDate: true,
  issueDate: true,
  grade: true,
  issuer: true,
  status: true,
  modules: true,
  studentId: false,
  photo: false,
};

export { DARBARTECH_CERTIFICATE_TEMPLATE, DEFAULT_PUBLIC_FIELDS } from "./darbartech-certificate-v1";

export const getTemplateById = (id: string, version?: string): TemplateConfig => {
  if (id === "darbartech-certificate") {
    if (version === "1.0.0") {
      return DARBARTECH_CERTIFICATE_TEMPLATE;
    }
    return DARBARTECH_CERTIFICATE_TEMPLATE_V2;
  }
  return DARBARTECH_CERTIFICATE_TEMPLATE_V2;
};
