import type { TemplateConfig } from "@/lib/types";

export const DARBARTECH_CERTIFICATE_TEMPLATE: TemplateConfig = {
  templateId: "darbartech-certificate",
  version: "1.0.0",
  rendererVersion: "certificate-engine 1.0.0",
  page: {
    width: 297,
    height: 210,
    unit: "mm",
    dpi: 300,
    orientation: "landscape",
    colorMode: "CMYK",
  },
  safeArea: {
    topMm: 8,
    rightMm: 8,
    bottomMm: 8,
    leftMm: 8,
  },
  moduleConstraints: {
    minCount: 3,
    maxCount: 6,
    maxTitleLength: 45,
    maxSubtitleLength: 80,
    area: {
      x: 42,
      y: 112,
      width: 213,
      height: 62,
      gap: 2,
    },
    item: {
      titleFont: "Helvetica-Bold",
      titleSize: 10,
      titleWeight: "bold",
      titleColor: "#0a2463",
      subtitleFont: "Helvetica",
      subtitleSize: 8,
      subtitleWeight: "normal",
      subtitleColor: "#3a3a3a",
      alignment: "left",
    },
  },
  fields: {
    mainTitle: {
      field: "mainTitle",
      type: "text",
      x: 0,
      y: 36,
      width: 297,
      height: 22,
      font: "Helvetica-Bold",
      fontSize: 28,
      weight: "bold",
      color: "#0a2463",
      alignment: "center",
      lineHeight: 1.2,
      letterSpacing: 2,
      maxLines: 1,
      minFontSize: 20,
      overflowPolicy: "shrink_then_reject",
      required: true,
    },
    mainSubtitle: {
      field: "mainSubtitle",
      type: "text",
      x: 0,
      y: 58,
      width: 297,
      height: 10,
      font: "Helvetica",
      fontSize: 11,
      weight: "normal",
      color: "#1e5f9e",
      alignment: "center",
      maxLines: 1,
      minFontSize: 9,
      overflowPolicy: "shrink_then_reject",
      required: true,
    },
    preRecipientText: {
      field: "preRecipientText",
      type: "text",
      x: 0,
      y: 74,
      width: 297,
      height: 8,
      font: "Helvetica-Oblique",
      fontSize: 10,
      weight: "normal",
      color: "#555555",
      alignment: "center",
      maxLines: 1,
      minFontSize: 8,
      overflowPolicy: "shrink_then_reject",
      required: true,
    },
    recipientName: {
      field: "recipientName",
      type: "text",
      x: 30,
      y: 82,
      width: 237,
      height: 22,
      font: "Helvetica-Bold",
      fontSize: 32,
      weight: "bold",
      color: "#0a2463",
      alignment: "center",
      lineHeight: 1.1,
      maxLines: 2,
      minFontSize: 18,
      overflowPolicy: "shrink_then_reject",
      required: true,
    },
    postRecipientLine: {
      field: "postRecipientLine",
      type: "text",
      x: 0,
      y: 105,
      width: 297,
      height: 7,
      font: "Helvetica",
      fontSize: 9,
      weight: "normal",
      color: "#888888",
      alignment: "center",
      maxLines: 1,
      minFontSize: 7,
      overflowPolicy: "shrink_then_reject",
      required: false,
    },
    programTitle: {
      field: "programTitle",
      type: "text",
      x: 42,
      y: 112,
      width: 213,
      height: 18,
      font: "Helvetica-Bold",
      fontSize: 14,
      weight: "bold",
      color: "#0a2463",
      alignment: "left",
      lineHeight: 1.2,
      maxLines: 2,
      minFontSize: 10,
      overflowPolicy: "shrink_then_reject",
      required: true,
    },
    duration: {
      field: "duration",
      type: "text",
      x: 42,
      y: 108,
      width: 213,
      height: 8,
      font: "Helvetica",
      fontSize: 9,
      weight: "normal",
      color: "#555555",
      alignment: "left",
      maxLines: 1,
      minFontSize: 7,
      overflowPolicy: "shrink_then_reject",
      required: true,
    },
    completionLabel: {
      field: "completionLabel",
      type: "text",
      x: 42,
      y: 178,
      width: 90,
      height: 8,
      font: "Helvetica",
      fontSize: 8,
      weight: "normal",
      color: "#666666",
      alignment: "left",
      maxLines: 1,
      minFontSize: 7,
      overflowPolicy: "shrink_then_reject",
      required: false,
    },
    completionDate: {
      field: "completionDate",
      type: "date",
      x: 42,
      y: 186,
      width: 90,
      height: 8,
      font: "Helvetica-Bold",
      fontSize: 10,
      weight: "bold",
      color: "#1a1a2e",
      alignment: "left",
      maxLines: 1,
      minFontSize: 8,
      overflowPolicy: "shrink_then_reject",
      required: false,
    },
    issueLabel: {
      field: "issueLabel",
      type: "text",
      x: 148,
      y: 178,
      width: 90,
      height: 8,
      font: "Helvetica",
      fontSize: 8,
      weight: "normal",
      color: "#666666",
      alignment: "left",
      maxLines: 1,
      minFontSize: 7,
      overflowPolicy: "shrink_then_reject",
      required: false,
    },
    issueDate: {
      field: "issueDate",
      type: "date",
      x: 148,
      y: 186,
      width: 90,
      height: 8,
      font: "Helvetica-Bold",
      fontSize: 10,
      weight: "bold",
      color: "#1a1a2e",
      alignment: "left",
      maxLines: 1,
      minFontSize: 8,
      overflowPolicy: "shrink_then_reject",
      required: true,
    },
    gradeLabel: {
      field: "gradeLabel",
      type: "text",
      x: 0,
      y: 178,
      width: 297,
      height: 8,
      font: "Helvetica",
      fontSize: 8,
      weight: "normal",
      color: "#666666",
      alignment: "center",
      maxLines: 1,
      minFontSize: 7,
      overflowPolicy: "shrink_then_reject",
      required: false,
    },
    grade: {
      field: "grade",
      type: "text",
      x: 0,
      y: 186,
      width: 297,
      height: 10,
      font: "Helvetica-Bold",
      fontSize: 14,
      weight: "bold",
      color: "#c9a227",
      alignment: "center",
      maxLines: 1,
      minFontSize: 10,
      overflowPolicy: "shrink_then_reject",
      required: false,
    },
    signatoryName: {
      field: "signatoryName",
      type: "text",
      x: 178,
      y: 184,
      width: 100,
      height: 8,
      font: "Helvetica-Bold",
      fontSize: 10,
      weight: "bold",
      color: "#0a2463",
      alignment: "center",
      maxLines: 1,
      minFontSize: 8,
      overflowPolicy: "shrink_then_reject",
      required: true,
    },
    signatoryLine: {
      field: "signatoryLine",
      type: "text",
      x: 178,
      y: 180,
      width: 100,
      height: 2,
      font: "Helvetica",
      fontSize: 1,
      weight: "normal",
      color: "#0a2463",
      alignment: "center",
      maxLines: 1,
      minFontSize: 1,
      overflowPolicy: "reject",
      required: false,
    },
    signatoryPosition: {
      field: "signatoryPosition",
      type: "text",
      x: 178,
      y: 192,
      width: 100,
      height: 8,
      font: "Helvetica-Oblique",
      fontSize: 8,
      weight: "normal",
      color: "#555555",
      alignment: "center",
      maxLines: 2,
      minFontSize: 6,
      overflowPolicy: "shrink_then_reject",
      required: true,
    },
    certificateNumberLabel: {
      field: "certificateNumberLabel",
      type: "text",
      x: 19,
      y: 195,
      width: 90,
      height: 6,
      font: "Helvetica",
      fontSize: 7,
      weight: "normal",
      color: "#666666",
      alignment: "left",
      maxLines: 1,
      minFontSize: 6,
      overflowPolicy: "shrink_then_reject",
      required: false,
    },
    certificateNumber: {
      field: "certificateNumber",
      type: "text",
      x: 19,
      y: 200,
      width: 90,
      height: 7,
      font: "Helvetica-Bold",
      fontSize: 9,
      weight: "bold",
      color: "#0a2463",
      alignment: "left",
      maxLines: 1,
      minFontSize: 7,
      overflowPolicy: "shrink_then_reject",
      required: true,
    },
    footerText: {
      field: "footerText",
      type: "text",
      x: 0,
      y: 198,
      width: 297,
      height: 8,
      font: "Helvetica",
      fontSize: 7,
      weight: "normal",
      color: "#888888",
      alignment: "center",
      lineHeight: 1.2,
      maxLines: 2,
      minFontSize: 5,
      overflowPolicy: "shrink_then_reject",
      required: false,
    },
    issuedBy: {
      field: "issuedBy",
      type: "text",
      x: 19,
      y: 188,
      width: 90,
      height: 6,
      font: "Helvetica-Bold",
      fontSize: 8,
      weight: "bold",
      color: "#0a2463",
      alignment: "left",
      maxLines: 2,
      minFontSize: 6,
      overflowPolicy: "shrink_then_reject",
      required: false,
    },
    issuerLogo: {
      field: "issuerLogo",
      type: "image",
      x: 19,
      y: 14,
      width: 28,
      height: 28,
      font: "",
      fontSize: 0,
      weight: "normal",
      color: "",
      alignment: "center",
      maxLines: 1,
      minFontSize: 0,
      overflowPolicy: "reject",
      required: false,
    },
  },
  staticAssets: {
    logo: "/logo.png",
    background: undefined,
    border: undefined,
  },
  qrConfig: {
    x: 250,
    y: 176,
    size: 28,
    errorCorrection: "M",
    margin: 1,
  },
  signatureConfig: {
    x: 178,
    y: 166,
    width: 100,
    height: 16,
    nameFont: "Helvetica-Bold",
    nameSize: 10,
    nameWeight: "bold",
    positionFont: "Helvetica-Oblique",
    positionSize: 8,
  },
  colors: {
    brandNavy: { cmyk: "90,70,0,60", hex: "#0a2463" },
    brandBlue: { cmyk: "80,45,10,0", hex: "#1e5f9e" },
    brandCyan: { cmyk: "65,20,5,0", hex: "#3e92cc" },
    brandGold: { cmyk: "15,35,85,5", hex: "#c9a227" },
    brandDark: { cmyk: "90,90,90,90", hex: "#1a1a2e" },
    black: { cmyk: "0,0,0,100", hex: "#000000" },
    white: { cmyk: "0,0,0,0", hex: "#ffffff" },
  },
};

export const getTemplateById = (id: string, version?: string): TemplateConfig => {
  if (id === "darbartech-certificate" && (!version || version === "1.0.0")) {
    return DARBARTECH_CERTIFICATE_TEMPLATE;
  }
  return DARBARTECH_CERTIFICATE_TEMPLATE;
};

export const DEFAULT_PUBLIC_FIELDS = {
  certificateNumber: true,
  recipientName: true,
  programTitle: true,
  duration: true,
  completionDate: true,
  issueDate: true,
  grade: true,
  issuer: true,
  status: true,
  modules: false,
  studentId: false,
  photo: false,
};
